name: Weather pipeline

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run script
        run: python weather_pipeline.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto update weather data" || echo "No changes"
          git push